### ISSUE TITLE
执行 getInfo.py会报错

### ISSUE THREAD

**Issue by jarryxy** [MiraculousB/not-in-campus#3]
[root@VM_0_16_centos python]# python3 getInfo.py 
14:22:50  HTTPSConnectionPool(host='student.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /my/getStudentSecretInfo.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9bb06d25b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
14:22:50  [Errno 2] No such file or directory: '/home/autopost/RUNLOG-2021-01-01.txt'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connection.py", line 136, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 557, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connection.py", line 217, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connection.py", line 145, in _new_conn
    raise NewConnectionError(
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9bb06d25b0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/adapters.py", line 368, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 608, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='student.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /my/getStudentSecretInfo.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9bb06d25b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 30, in postFormNightlocate
    res = requests.get(url=url, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/adapters.py", line 442, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='student.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /my/getStudentSecretInfo.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9bb06d25b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 78, in main
    info_dict = postFormNightlocate(value[1])
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 34, in postFormNightlocate
    log(e)
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 24, in log
    with open ("/home/autopost/"+strday,"a",encoding='utf-8') as logg:
FileNotFoundError: [Errno 2] No such file or directory: '/home/autopost/RUNLOG-2021-01-01.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 129, in <module>
    main()
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 111, in main
    log(e)
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 24, in log
    with open ("/home/autopost/"+strday,"a",encoding='utf-8') as logg:
FileNotFoundError: [Errno 2] No such file or directory: '/home/autopost/RUNLOG-2021-01-01.txt'
[root@VM_0_16_centos python]# python3 autoEnroll.py 
You have new mail in /var/spool/mail/root
[root@VM_0_16_centos python]# python3 getInfo.py 
14:37:21  HTTPSConnectionPool(host='student.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /my/getStudentSecretInfo.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd0bc24b5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
14:37:21  [Errno 2] No such file or directory: '/home/autopost/RUNLOG-2021-01-01.txt'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connection.py", line 136, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 557, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connection.py", line 217, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connection.py", line 145, in _new_conn
    raise NewConnectionError(
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd0bc24b5b0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/adapters.py", line 368, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 608, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='student.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /my/getStudentSecretInfo.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd0bc24b5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 30, in postFormNightlocate
    res = requests.get(url=url, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/adapters.py", line 442, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='student.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /my/getStudentSecretInfo.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd0bc24b5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 78, in main
    info_dict = postFormNightlocate(value[1])
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 34, in postFormNightlocate
    log(e)
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 24, in log
    with open ("/home/autopost/"+strday,"a",encoding='utf-8') as logg:
FileNotFoundError: [Errno 2] No such file or directory: '/home/autopost/RUNLOG-2021-01-01.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 129, in <module>
    main()
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 111, in main
    log(e)
  File "/www/wwwroot/not-in-campus/python/getInfo.py", line 24, in log
    with open ("/home/autopost/"+strday,"a",encoding='utf-8') as logg:
FileNotFoundError: [Errno 2] No such file or directory: '/home/autopost/RUNLOG-2021-01-01.txt'

**Comment by jarryxy** [comment]
> [root@VM_0_16_centos python]# python3 getInfo.py
> 14:22:50 HTTPSConnectionPool(host='student.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /my/getStudentSecretInfo.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9bb06d25b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> 14:22:50 [Errno 2] No such file or directory: '/home/autopost/RUNLOG-2021-01-01.txt'
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connection.py", line 136, in _new_conn
> conn = connection.create_connection(
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/util/connection.py", line 67, in create_connection
> for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
> File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
> for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 557, in urlopen
> httplib_response = self._make_request(conn, method, url,
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
> self._validate_conn(conn)
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
> conn.connect()
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connection.py", line 217, in connect
> conn = self._new_conn()
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connection.py", line 145, in _new_conn
> raise NewConnectionError(
> requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9bb06d25b0>: Failed to establish a new connection: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/adapters.py", line 368, in send
> resp = conn.urlopen(
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 608, in urlopen
> retries = retries.increment(method, url, error=e, _pool=self,
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/util/retry.py", line 273, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='student.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /my/getStudentSecretInfo.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9bb06d25b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 30, in postFormNightlocate
> res = requests.get(url=url, headers=headers)
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/api.py", line 71, in get
> return request('get', url, params=params, **kwargs)
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/api.py", line 57, in request
> return session.request(method=method, url=url, **kwargs)
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/sessions.py", line 475, in request
> resp = self.send(prep, **send_kwargs)
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/sessions.py", line 585, in send
> r = adapter.send(request, **kwargs)
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/adapters.py", line 442, in send
> raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='student.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /my/getStudentSecretInfo.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9bb06d25b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 78, in main
> info_dict = postFormNightlocate(value[1])
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 34, in postFormNightlocate
> log(e)
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 24, in log
> with open ("/home/autopost/"+strday,"a",encoding='utf-8') as logg:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/autopost/RUNLOG-2021-01-01.txt'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 129, in
> main()
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 111, in main
> log(e)
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 24, in log
> with open ("/home/autopost/"+strday,"a",encoding='utf-8') as logg:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/autopost/RUNLOG-2021-01-01.txt'
> [root@VM_0_16_centos python]# python3 autoEnroll.py
> You have new mail in /var/spool/mail/root
> [root@VM_0_16_centos python]# python3 getInfo.py
> 14:37:21 HTTPSConnectionPool(host='student.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /my/getStudentSecretInfo.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd0bc24b5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> 14:37:21 [Errno 2] No such file or directory: '/home/autopost/RUNLOG-2021-01-01.txt'
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connection.py", line 136, in _new_conn
> conn = connection.create_connection(
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/util/connection.py", line 67, in create_connection
> for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
> File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
> for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 557, in urlopen
> httplib_response = self._make_request(conn, method, url,
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
> self._validate_conn(conn)
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
> conn.connect()
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connection.py", line 217, in connect
> conn = self._new_conn()
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connection.py", line 145, in _new_conn
> raise NewConnectionError(
> requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd0bc24b5b0>: Failed to establish a new connection: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/adapters.py", line 368, in send
> resp = conn.urlopen(
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/connectionpool.py", line 608, in urlopen
> retries = retries.increment(method, url, error=e, _pool=self,
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/packages/urllib3/util/retry.py", line 273, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='student.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /my/getStudentSecretInfo.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd0bc24b5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 30, in postFormNightlocate
> res = requests.get(url=url, headers=headers)
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/api.py", line 71, in get
> return request('get', url, params=params, **kwargs)
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/api.py", line 57, in request
> return session.request(method=method, url=url, **kwargs)
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/sessions.py", line 475, in request
> resp = self.send(prep, **send_kwargs)
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/sessions.py", line 585, in send
> r = adapter.send(request, **kwargs)
> File "/usr/local/lib/python3.9/site-packages/requests-2.9.2-py3.9.egg/requests/adapters.py", line 442, in send
> raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='student.wozaixiaoyuan.com', port=443): Max retries exceeded with url: /my/getStudentSecretInfo.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd0bc24b5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 78, in main
> info_dict = postFormNightlocate(value[1])
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 34, in postFormNightlocate
> log(e)
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 24, in log
> with open ("/home/autopost/"+strday,"a",encoding='utf-8') as logg:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/autopost/RUNLOG-2021-01-01.txt'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 129, in
> main()
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 111, in main
> log(e)
> File "/www/wwwroot/not-in-campus/python/getInfo.py", line 24, in log
> with open ("/home/autopost/"+strday,"a",encoding='utf-8') as logg:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/autopost/RUNLOG-2021-01-01.txt'
